# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AspectF# - .NET F#-based Aspect-oriented Functional Programming Language 
email: developers@fsharp.company
description: > # this means to ignore newlines until "baseurl:"
  In the hunt for .NET F#-based Aspect-oriented Functional Programming Language
baseurl: "/aspectfsharp" # the subpath of your site, e.g. /blog
url: "http://www.naseukoly.cz" # the base hostname & protocol for your site
twitter_username: NaseUkolyCZ
github_username:  NaseUkolyCZ

# Build settings
markdown: kramdown
