# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.naseukoly.cz/aspectfsharp/
gitlocation: https://github.com/NaseUkolyCZ/aspectfsharp.git
gitbranch: gh-pages
title: AspectF# - .NET F#-based Aspect-oriented Functional Programming Language
description: >
    This project is about the path to find or create .NET F#-based
    aspect-oriented functional programming language.
    It seems except for AspectML and AspectFun this area is not explored too much.

source: source/
blog: source/blog/
blogIndex: source/blog/index.cshtml
layouts: layouts
content: content
template: tools/empty-template.html
output: output/
deploy: deploy
themes: themes
